# Generated by Django 4.2.4 on 2023-08-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, unique=True)),
                ('size_type', models.CharField(choices=[('CLOTHING', 'Clothing'), ('SHOE', 'Shoe')], default='CLOTHING', max_length=10)),
            ],
        ),
    ]
